version: "3"
networks:
  futsel_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futsel_backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=mysql_db
      - DB_DATABASE=futsel_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - futsel_network
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        composer install
        php artisan migrate
        php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=futsel_db
      - MYSQL_USER=futsel_user
      - MYSQL_PASSWORD=futsel_password
    networks:
      - futsel_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root"]
      interval: 5s
      timeout: 5s
      retries: 5
